services:
  plex:
    image: lscr.io/linuxserver/plex:${TAG:-1.43.2}
    container_name: ${CNTNR:-plex}
    network_mode: host
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ-Europe/Vienna}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ${CNFG_DIR}/config:/config
      - ${TRANSCODE_DIR}/transcode:/transcode
      - ${MNT_DIR}/PlexMedia/data/media/tv:/tv
      - ${MNT_DIR}/PlexMedia/data/media/movies:/movies
    restart: unless-stopped
