services:
  traefik:
    image: traefik:${TAG:-v3.6}
    container_name: ${CNTNR:-traefik}
    restart: ${RESTART:-unless-stopped}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - ${HOST_PORT_HTTP:-80}:80
      - ${HOST_PORT_HTTPS:-443}:443
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token
    secrets:
      - cf_api_token
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_GITSYNC_DIR}/data:/etc/traefik:ro
      - ${TRAEFIK_DIR}/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.adm.${DOMAIN}`) || Host(`traefik-adm-${DOMAIN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.adm.${DOMAIN}`) || Host(`traefik-adm-${DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=prx.${DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.prx.${DOMAIN},*.api.${DOMAIN},*.app.${DOMAIN},*.pve.${DOMAIN},*.dbs.${DOMAIN},*.web.${DOMAIN},*.adm.${DOMAIN},*.dsh.${DOMAIN}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

secrets:
  cf_api_token:
    file: ${TRAEFIK_GITSYNC_DIR}/data/cf_api_token.txt
    
networks:
  proxy:
    external: true
