services:
  postgres:
    image: postgres:${DB_TAG:-16-alpine}
    container_name: ${DB_CNTNR:-dockhand-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dockhand}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-dockhand}
    volumes:
      - ${DIR:-/home/ubuntu/dockhand}/postgres_data:/var/lib/postgresql/data

  dockhand:
    image: fnsys/dockhand:${TAG:-v1.0.24}
    container_name: ${CNTNR:-dockhand}
    ports:
      - ${HOST_PORT:-3000}:3000
    environment:
      DATABASE_URL: postgres://dockhand:${POSTGRES_PASSWORD}@postgres:5432/dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DIR:-/home/ubuntu/dockhand}/dockhand_data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
