x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:
  vpn-charlie:
    <<: *logging
    image: qmcgaw/gluetun:${VPN_TAG:-v3.41.1}
    container_name: ${VPN_CHARLIE_CNTNR:-vpn-charlie}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_PROTOCOL: ${VPN_PROTOCOL:-tcp}
      UPDATER_PERIOD: 24h
      HEALTH_VPN_DURATION_INITIAL: ${HEALTH_VPN_DURATION_INITIAL:-10s}
      VPN_PORT_FORWARDING: "on"
      PORT_FORWARD_ONLY: "true"
      DNS_UPSTREAM_RESOLVER_TYPE: plain
      DNS_UPSTREAM_PLAIN_ADDRESSES: 1.1.1.1:53,9.9.9.9:53
      VPN_PORT_FORWARDING_UP_COMMAND: "/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORT}},\\\"random_port\\\":false,\\\"upnp\\\":false}\" http://127.0.0.1:8080/api/v2/app/setPreferences'"
      VPN_PORT_FORWARDING_DOWN_COMMAND: "/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data \"json={\\\"listen_port\\\":0}\" http://127.0.0.1:8080/api/v2/app/setPreferences'"
      SERVER_REGIONS: ${VPN_CHARLIE_REGIONS:-Austria,France,Croatia}
      TZ: ${TZ}
    ports:
      - "${QBIT_CHARLIE_WEBUI_PORT:-8083}:8080"
    volumes:
      - ${CNFG_DIR:-.}/gluetun:/gluetun

  qbit-charlie:
    <<: *logging
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_TAG:-5.1.4}
    container_name: ${QBIT_CHARLIE_CNTNR:-qbit-charlie}
    network_mode: "service:vpn-charlie"
    restart: unless-stopped
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ}
      WEBUI_PORT: "8080"
    volumes:
      - ${CNFG_DIR:-.}/qbit/config:/config
      - ${MNT_DIR}/torrents:/data/torrents
    depends_on:
      vpn-charlie:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
